image:
    - Visual Studio 2019

cache:
    - '%USERPROFILE%\.conan\data -> conanfile.txt'
    - C:\.conan -> conanfile.txt

install:
    - cmd: choco install conan
    - cmd: refreshenv

build_script:
    - cmd: mkdir build && cd build
    - cmd: cmake -G "Visual Studio 16 2019" ..
    - cmd: cmake --build . --config Release

test_script:
    - cmd: Release\emoji2image.exe
