image:
    - Visual Studio 2019

cache:
    - '%USERPROFILE%\.conan\data -> CMakeLists.txt'

install:
    - cmd: choco install conan
    - cmd: refreshenv

platform:
    - x64

configuration:
    - Debug
    - Release

matrix:
    fast_finish: true

build_script:
    - cmd: mkdir build && cd build
    - cmd: cmake ..
    - cmd: cmake --build .

test_script:
    - cmd: '%CONFIGURATION%\emoji2image.exe'
